name: riverpod_todo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.10
  freezed_annotation: ^2.4.1
  intl: ^0.19.0
  json_annotation: ^4.8.1
  riverpod_annotation: ^2.3.4

dev_dependencies:
  build_runner: ^2.4.8
  custom_lint: ^0.6.2
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  pedantic_mono: any
  riverpod_generator: ^2.3.11
  riverpod_lint: ^2.3.9

flutter:
  uses-material-design: true
